import type { NextPage } from "next";
import Head from "next/head";
import CTA from "../component/Landing/CTA/CTA";
import Footer from "../component/Footer/Footer";
import Header from "../component/Landing/Header/Header";
import Main from "../component/Landing/Main.tsx/Main";
import ValueComp from "../component/Landing/Value/ValueComp";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>PlinPlant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Main />
        <ValueComp />
        <CTA />
        <Footer />
      </main>
    </>
  );
};

export default Home;
